name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        config: [Debug]

    steps:
    - uses: actions/checkout@v4

    - name: Configure (use clang)
      run: |
        mkdir -p build
        cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
      shell: bash

    - name: Build
      run: |
        cmake --build build --config ${{ matrix.config }}
      shell: bash

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure -C ${{ matrix.config }}
      shell: bash
